#!/usr/bin/env bash

while getopts d: OPT
do
  case $OPT in
    d)
      delimiter="$OPTARG"
      ;;
    *)
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

sed -E "s/[${delimiter:- 	}]+/ | /g;s/^/| /;s/$/ |/g" | sed -E '1p;1s/\|[^\|]+/| --- /g'

